setwd("~/Desktop/R")
subdata <- file("household_power_consumption.txt")
plot1 <- read.table(text = grep("^[1,2]/2/2007", readLines(subdata), value = TRUE), col.names = c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), header = TRUE, sep = ";", na.strings = "?",nrows = 2075259, check.names=FALSE, stringsAsFactors = FALSE, comment.char = "", quote = '\"')
png(filename='plot3.png',width=480,height=480,units='px')
with(plot1, {plot(Sub_metering_1 ~ datetime, type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
  lines(Sub_metering_2 ~ datetime, col = 'Red')
  lines(Sub_metering_3 ~ datetime, col = 'Blue') })
legend("topright", col = c("black", "red", "blue"), lty = 1, lwd = 1, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()