setwd("~/Desktop/R")
subdata <- file("household_power_consumption.txt")
plot1 <- read.table(text = grep("^[1,2]/2/2007", readLines(subdata), value = TRUE), col.names = c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), header = TRUE, sep = ";", na.strings = "?",nrows = 2075259, check.names=FALSE, stringsAsFactors = FALSE, comment.char = "", quote = '\"')
png(filename='plot4.png',width=480,height=480,units='px')
par(mfrow=c(2,2))
plot(plot1$Global_active_power ~ plot1$datetime, type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
plot(plot1$Voltage ~ plot1$datetime, type = "l", ylab = "Voltage", xlab = "datetime")
plot(plot1$Sub_metering_1 ~ plot1$datetime, type = "l", ylab = "Energy sub metering", col="black" ,xlab = "")
with(lines(plot1$Sub_metering_2 ~ plot1$datetime, col = "red"))
with(lines(plot1$Sub_metering_3 ~ plot1$datetime, col = "blue"))
with(legend("topright", col = c("black", "red", "blue"), lty = 1, lwd = 1, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3")))
plot(plot1$Global_reactive_power ~ plot1$datetime, type = "l", ylab = "Global_rective_power", xlab = "datetime")
dev.off()